repos:
  - repo: https://github.com/bwhmather/ssort
    rev: 0.12.4
    hooks:
      - id: ssort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi]
